# Generated by Django 4.2 on 2023-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='main_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.URLField(),
        ),
    ]
